server:
  port: 8081

spring:
  application:
    name: stream-processor
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: realtime-analytics-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.realtime.common.dto.EventDTO
app:
  kafka:
    topic: events
logging:
  level:
    root: INFO